### ISSUE TITLE
Screen shake

### ISSUE THREAD

**Issue by scottbass47** [scottbass47/gsts#28]
What should trigger it?

**Comment by henryjeff** [comment]
With what is in the game right now, I think the only things that would trigger screen shake should be getting hit (taking damage) and firing your weapon. More specifically, completing Issue #24 would allow for a really great way to add in screen shake wherever we really want (I am a big fan of global event systems)

Another great resource I found pertaining to screen shake is [this website](https://jonny.morrill.me/en/blog/gamedev-how-to-implement-a-camera-shake-effect/ )

I didn't look into their specifics as to how they calculate the shake, but after playing around with the example pretty extensively I can say it looks very natural. If we use their implementation here are the values I came up with for both situations we might want screen shake:

Shooting:
- Duration (Seconds) : 0.1
- Frequency  (Hertz) : 30? The lower gives it a more sense of control
- Amplitude (Pixels) : 5

Taking Damage:
- Duration (Seconds) : 0.3
- Frequency  (Hertz) : 22
- Amplitude (Pixels) : 7

All of these values can be fine-tuned over time and If we want, they could even be affected by different gun attachments we add in down the line.
